spring.application.name=lifeline

spring.data.mongodb.uri=mongodb://localhost:27017/lifeline_db

server.port=8080

# =======================
# Spring Mail Config
# =======================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=sejalshinde6552@gmail.com
spring.mail.password=yrfvwjxfebmlyqhf
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.base-url=http://localhost:8080

jwt.secret=paste_a_long_random_string_here_at_least_32_characters
jwt.expiration=3600000

jwt.refresh-expiration=604800000